BF(workaround): pip no longer can install release tarball for 0.17.x - use 0.18.0
error was

	Processing ./0.17.2.tar.gz
	  Installing build dependencies: started
	  Installing build dependencies: finished with status 'done'
	  Getting requirements to build wheel: started
	  Getting requirements to build wheel: finished with status 'error'
	  error: subprocess-exited-with-error

	  × Getting requirements to build wheel did not run successfully.
	  │ exit code: 1
	  ╰─> [1 lines of output]
		  error in datalad setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
		  [end of output]

	  note: This error originates from a subprocess, and is likely not a problem with pip.
	error: subprocess-exited-with-error

	× Getting requirements to build wheel did not run successfully.
	│ exit code: 1
	╰─> See above for output.

	note: This error originates from a subprocess, and is likely not a problem with pip.
	Error: Process completed with exit code 1.

upgrades of pip/setuptools didn't happen and we used to install just fine like
that before (6 month ago, no logs no longe ravialble AFAIK)